# Numpy Review Problem Set

In [2]:
import numpy as np

#### Create an all zero numpy array of size 1000

In [7]:
# write code here
z = np.zeros(1000)

#### Create a numpy array from all digits between [0,1000) that are divisible by five

In [6]:
# write code here
a = np.arange(0, 1001, 5)
print(a)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140  145
  150  155  160  165  170  175  180  185  190  195  200  205  210  215  220
  225  230  235  240  245  250  255  260  265  270  275  280  285  290  295
  300  305  310  315  320  325  330  335  340  345  350  355  360  365  370
  375  380  385  390  395  400  405  410  415  420  425  430  435  440  445
  450  455  460  465  470  475  480  485  490  495  500  505  510  515  520
  525  530  535  540  545  550  555  560  565  570  575  580  585  590  595
  600  605  610  615  620  625  630  635  640  645  650  655  660  665  670
  675  680  685  690  695  700  705  710  715  720  725  730  735  740  745
  750  755  760  765  770  775  780  785  790  795  800  805  810  815  820
  825  830  835  840  845  850  855  860  865  870  875  880  885  890  895
  900  905  910  915  920  925  930  935  940  945  950  955  960  965  970
  975  980  

#### Assign a 1 to every element divisible by 5 in the all zero array

In [10]:
# write code here
b = z % 5 == 0
z[b] = 1
print(z[:5])

[ 1.  1.  1.  1.  1.]


#### Below is the grades for 6 students, convert to a numpy array

In [13]:
grades = [90, 94, 88, 80, 78, 85]
# write code here
grades = np.array(grades)

#### Scale every grade below 90 up by 2 points

In [14]:
# write code here
b = grades < 90
grades[b] += 2
print(grades)

[90 94 90 82 80 87]


#### Create a 10 by 10 matrix with 1 on the border 0 within the border

In [19]:
# write code here
ten = np.ones((10, 10))
ten[1:-1, 1:-1] = 0
print(ten)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


## Challenge Problems

#### Create an 10 by 10 checkerboard matrix in three lines of code.
Below is an example of a 3 by 3 checkerboard matrix

In [ ]:
# [0 1 0]
# [1 0 1]
# [0 1 0]

In [35]:
# write code here
ten = np.ones((10, 10))

ten[0:-1:2, 0:-1:2] = 0
ten[1::2, 1::2] = 0
print(ten)

[[ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.  1.  0.]]


#### Assume that you have an MxM array, a, and a number, n (where n < M). Using array attributes and slicing, print out the nxn subarray at the center of a (example below for n=3, M=5   -- you may assume that n is odd and that a has an odd number of rows and columns) 

In [37]:
#
# 0 0 0 0 0
# 0 X X X 0      X X X
# 0 X X X 0 ---> X X X
# 0 X X X 0      X X X
# 0 0 0 0 0
a = np.random.random((5, 5))
print(a)

[[ 0.59396952  0.95667484  0.02489916  0.32681381  0.5620066 ]
 [ 0.14375566  0.08906005  0.98016359  0.65270418  0.00997012]
 [ 0.25611891  0.14922063  0.36495177  0.91086169  0.70133683]
 [ 0.30943566  0.08507852  0.24735757  0.5457619   0.22625575]
 [ 0.15024232  0.40141253  0.60524511  0.23199982  0.44222914]]


In [39]:
# write code her

def thing(a, n):
    M = len(a)
    x = (M - n) / 2
    return a[x: M - x, x: M - x]
thing(a, 3)

/Users/victor/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


array([[ 0.08906005,  0.98016359,  0.65270418],
       [ 0.14922063,  0.36495177,  0.91086169],
       [ 0.08507852,  0.24735757,  0.5457619 ]])